trigger:
- main

variables:
  azureSubscription: 'PERIFERIA_IT_GROUP_CCB4' # Asegúrate de que esta conexión funcione
  webAppName: 'AS-MESA-SERVICIOS'
  nodeVersion: '20.x'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseNode@1
      inputs:
        version: $(nodeVersion)
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install and Build'

    - script: |
        npm prune --omit=dev
      displayName: 'Remove dev dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/app.zip'
      artifact: drop

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureCLI@2
      displayName: 'Configure App Settings'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config appsettings set \
            --name $(webAppName) \
            --resource-group $(az webapp show --name $(webAppName) --query resourceGroup -o tsv) \
            --settings PORT=8787 WEBSITES_PORT=8787 WEBSITES_CONTAINER_START_TIME_LIMIT=1800 SCM_DO_BUILD_DURING_DEPLOYMENT=false

          az webapp config set \
            --name $(webAppName) \
            --resource-group $(az webapp show --name $(webAppName) --query resourceGroup -o tsv) \
            --startup-file "npm run start"

    - task: AzureCLI@2
      displayName: 'Deploy ZIP to App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp deploy \
            --name $(webAppName) \
            --resource-group $(az webapp show --name $(webAppName) --query resourceGroup -o tsv) \
            --src-path "$(Pipeline.Workspace)/drop/app.zip" \
            --type zip

