/**
 * Preguntas frecuentes extraídas de `public/Consulta Soporte.xlsx`.
 * Mantener alineado con ese archivo si se actualiza.
 */
export type FaqItem = {
  id: string
  title: string
  category: string
  content: string
}

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: 'maquina-password',
    title: 'No puedo ingresar a la máquina',
    category: 'Cambio contraseña',
    content: [
      'SI NO PUEDE ENTRAR AL COMPUTADOR PORQUE LA CONTRASEÑA NO FUNCIONA O SE LE OLVIDÓ, LO MÁS SEGURO ES HABLAR CON SOPORTE.',
      'CUANDO CAMBIA LA CONTRASEÑA EN EL CORREO, EL COMPUTADOR NO SINCRONIZA LOS SERVICIOS AUTOMÁTICAMENTE. POR ESO:',
      'DEBE CONECTAR LA VPN DESDE LA PANTALLA DE INICIO DE SESIÓN.',
      'LUEGO ESCRIBA LA MISMA CONTRASEÑA QUE USA PARA ABRIR EL CORREO.',
      'ASÍ EL EQUIPO ACTUALIZA CLAVE Y LE DEJARÁ ENTRAR.',
    ].join('\n\n'),
  },
  {
    id: 'vpn',
    title: 'No puedo ingresar a la VPN',
    category: 'Cambio contraseña',
    content: [
      'SI LA VPN RECHAZA EL ACCESO, ES POSIBLE QUE ESTÉ TOMANDO UNA CONTRASEÑA ANTIGUA. SE DEBE REALIZAR EL CAMBIO DE CONTRASEÑA Y LUEGO VOLVER A INTENTAR EL ACCESO.',
      'DESPUÉS DE CAMBIAR LA CONTRASEÑA, PUEDE TARDAR VARIOS MINUTOS EN SINCRONIZAR LA VPN. SE DEBE VERIFICAR EL TIEMPO TRANSCURRIDO, Y SI YA PASÓ UN PERIODO RAZONABLE, ES POSIBLE QUE SE TRATE DE OTRO TIPO DE FALLA.',
    ].join('\n\n'),
  },
  {
    id: 'correo-login',
    title: 'No puedo ingresar al correo',
    category: 'Cambio contraseña',
    content:
      'SI EL CORREO NO PERMITE EL ACCESO A PESAR DE USAR LA CONTRASEÑA CORRECTA, LA CUENTA PODRÍA ESTAR BLOQUEADA O PRESENTAR UN ERROR EN EL SISTEMA. SOPORTE PUEDE VALIDAR EL ESTADO DE LA CUENTA Y REALIZAR EL DESBLOQUEO',
  },
  {
    id: 'correos-no-llegan',
    title: 'No me llegan correos',
    category: 'Problema con el correo',
    content: [
      'SI NO HAY CONEXIÓN A INTERNET, EL CORREO NO PODRÁ RECIBIR NI ACTUALIZAR LOS MENSAJES. SE DEBE VERIFICAR SI LAS PÁGINAS WEB CARGAN CORRECTAMENTE.',
      'SI LA DIRECCIÓN DE CORREO ESTÁ MAL ESCRITA, LOS MENSAJES NO SERÁN ENTREGADOS. SE DEBE CONFIRMAR QUE NO FALTEN LETRAS, NÚMEROS O PUNTOS.',
      'LA APLICACIÓN PUEDE QUEDAR SINCRONIZADA INCORRECTAMENTE. SE RECOMIENDA CERRARLA COMPLETAMENTE Y ABRIRLA DE NUEVO PARA FORZAR LA ACTUALIZACIÓN DE LOS MENSAJES.',
      'SI EL CAMBIO DE CONTRASEÑA SE REALIZÓ RECIENTEMENTE, LA APLICACIÓN PODRÍA SEGUIR USANDO LA CONTRASEÑA ANTIGUA. SE DEBE CERRAR SESIÓN EN LA APLICACIÓN E INICIARLA NUEVAMENTE CON LA CONTRASEÑA ACTUAL.',
    ].join('\n\n'),
  },
  {
    id: 'pc-no-enciende',
    title: 'El PC no enciende',
    category: 'Revisión PC',
    content: [
      'SE DEBE VERIFICAR QUE EL CARGADOR ESTÉ CONECTADO ADECUADAMENTE TANTO AL EQUIPO COMO A LA TOMA ELÉCTRICA. AUNQUE PAREZCA CONECTADO, PUEDE QUE NO ESTÉ HACIENDO CONTACTO CORRECTAMENTE.',
      'LOS LEDS DEL EQUIPO INDICAN SI RECIBE ENERGÍA. SI NO HAY NINGUNA LUZ ENCENDIDA, ES POSIBLE QUE EL EQUIPO NO ESTÉ RECIBIENDO CORRIENTE.',
      'SE DEBE MANTENER PRESIONADO EL BOTÓN DE ENCENDIDO DURANTE 10–15 SEGUNDOS HASTA QUE EL EQUIPO SE APAGUE POR COMPLETO. LUEGO, SE VUELVE A ENCENDER PARA REINICIAR SUS PROCESOS INTERNOS.',
    ].join('\n\n'),
  },
  {
    id: 'pc-sin-internet',
    title: 'El PC no tiene Internet',
    category: 'Revisión PC',
    content: [
      'REINICIAR EL EQUIPO PERMITE REESTABLECER EL ADAPTADOR DE RED Y RECONOCER NUEVAMENTE LA CONEXIÓN WIFI. ESTA ACCIÓN SUELE SOLUCIONAR PROBLEMAS DE CONEXIÓN.',
      'SI EL PROBLEMA CONTINÚA, PODRÍA SER UNA FALLA EN EL ADAPTADOR, LA RED O LA CONFIGURACIÓN. SOPORTE REALIZARÁ UN DICTAMEN DEL ERROR.',
    ].join('\n\n'),
  },
  {
    id: 'equipo-lento-windows',
    title: 'Equipo lento — Windows Update y controladores',
    category: 'Revisión PC',
    content: [
      '1. ABRIR CONFIGURACIÓN — PRESIONE EL BOTÓN INICIO EN LA ESQUINA INFERIOR IZQUIERDA Y LUEGO SELECCIONE CONFIGURACIÓN (EL ICONO DEL ENGRANAJE).',
      '2. IR A LA SECCIÓN “WINDOWS UPDATE” — EN EL PANEL DE LA IZQUIERDA, SELECCIONE WINDOWS UPDATE. AHÍ SE MUESTRA TODO LO RELACIONADO CON ACTUALIZACIONES.',
      '3. HACER CLIC EN “BUSCAR ACTUALIZACIONES” — PRESIONE EL BOTÓN BUSCAR ACTUALIZACIONES. WINDOWS EMPEZARÁ A VERIFICAR SI HAY: ACTUALIZACIONES IMPORTANTES, MEJORAS DEL SISTEMA, ACTUALIZACIONES DE CONTROLADORES.',
      '4. ABRIR LA OPCIÓN “OPCIONES AVANZADAS” — DEBAJO DE WINDOWS UPDATE, ENTRE A OPCIONES AVANZADAS. ALLÍ ENCONTRARÁ LA SECCIÓN LLAMADA: ACTUALIZACIONES OPCIONALES.',
      '5. IR A “ACTUALIZACIONES OPCIONALES” — EN ESTA SECCIÓN WINDOWS MUESTRA CONTROLADORES QUE NO SON OBLIGATORIOS, PERO QUE SÍ MEJORAN EL RENDIMIENTO DEL EQUIPO.',
      '6. SELECCIONAR “ACTUALIZACIONES DE CONTROLADORES” — EN ESTA PARTE WINDOWS LE MOSTRARÁ UNA LISTA DE CONTROLADORES DISPONIBLES, COMO: CONTROLADOR DE WIFI, CONTROLADOR DE BLUETOOTH, VÍDEO / GPU, SONIDO, CHIPSET, TECLADO / TOUCHPAD, OTROS DISPOSITIVOS. SELECCIONE TODOS LOS CONTROLADORES DISPONIBLES.',
      '7. PRESIONAR “DESCARGAR E INSTALAR” — WINDOWS INSTALARÁ AUTOMÁTICAMENTE LOS CONTROLADORES CORRECTOS.',
      '8. REINICIAR EL EQUIPO — UNA VEZ TERMINADO EL PROCESO, REINICIE EL PC PARA QUE LOS CAMBIOS SE APLIQUEN. ESTO FINALIZA LA ACTUALIZACIÓN Y MEJORA EL RENDIMIENTO.',
    ].join('\n\n'),
  },
  {
    id: 'equipo-lento-temp',
    title: 'Equipo lento — Limpiar carpeta temporal (%TEMP%)',
    category: 'Revisión PC',
    content: [
      'DESINSTALAR APLICACIONES QUE YA NO SE USAN.',
      '1. ABRIR EJECUTAR: PRESIONE LAS TECLAS WINDOWS + R AL MISMO TIEMPO. 2. ESCRIBIR EL COMANDO EN LA VENTANA QUE APARECE: %TEMP% Y PRESIONE ENTER. 3. SE ABRIRÁ UNA CARPETA LLENA DE ARCHIVOS; TODO LO QUE APARECE AHÍ ES BASURA TEMPORAL QUE EL SISTEMA YA NO NECESITA. 4. SELECCIONAR TODO: PRESIONE CTRL + E O CTRL + A PARA SELECCIONAR TODOS LOS ARCHIVOS. 5. ELIMINAR TODO: PRESIONE SHIFT + SUPR PARA ELIMINARLOS DE MANERA PERMANENTE. SI HAY ARCHIVOS QUE NO SE PUEDEN BORRAR, ES NORMAL; SIGNIFICA QUE ESTÁN SIENDO USADOS POR EL SISTEMA. Simplemente OMÍTALOS.',
    ].join('\n\n'),
  },
  {
    id: 'permisos-admin',
    title: 'Permisos de administrador',
    category: 'Escalamiento',
    content:
      'DEBE VENIR LA APROBACIÓN PRIMERO POR EL LÍDER DE TORRE; CUANDO ESTÉN LOS PERMISOS AUTORIZADOS INFORMAR A SOPORTE Y CUANDO SOPORTE CONFIRME LOS PERMISOS, DEBE CERRAR SESIÓN DEL PC, LEVANTAR LA VPN ANTES DE INICIAR SESIÓN (ES EL LOGO DE UN CANDADO EN LA PANTALLA DE BLOQUEO), INICIAR SESIÓN EN LA VPN Y DESPUÉS INICIAR SESIÓN EN EL PC Y YA PERMITIRÁ EL ACCESO CON PERMISOS ADMIN ACTIVOS.',
  },
  {
    id: 'bloqueo-app',
    title: 'Bloqueo de aplicación',
    category: 'Revisión PC',
    content:
      'SI HAY UNA APP QUE SE QUEDÓ "PEGADA" O BLOQUEADA Y NO PERMITE USARLA, DEBERÁ BUSCAR EN EL CAJÓN DE APLICACIONES EL ADMINISTRADOR DE TAREAS Y BUSCAR EL APLICATIVO QUE ESTÁ PRESENTANDO EL BLOQUEO, DARLE CLIC DERECHO SOBRE EL APLICATIVO Y SELECCIONAR LA OPCIÓN FINALIZAR TAREA, Y VOLVER A ABRIR LA APLICACIÓN.',
  },
]

export function promptFromFaq(item: FaqItem): string {
  return `[Consulta desde FAQ: ${item.title}]\n\n${item.content}`
}
